---
title: '`riycf` Package'
author: "Independent Study Planning"
fontsize: 12pt
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
header-includes: \usepackage{pdfpages}
geometry: margin=0.5in
fig_crop: no
---


## Background Information 

The first 1,000 days of life (from pregnancy to a child's 2nd birthday) are critical for addressing childhood malnutrition, especially stunting. The infant and young child feeding practices (IYCF) are largely overlapped with that period as it covers the breastfeeding and complementary feeding practices for the first two years of a child's life. And it also has a significant impact on childhood health, nutrition outcome, and survival. Therefore, measuring IYCF practices is also critical for countries to monitor progress toward their respective Sustainable Development Goal - 2 , and the development agencies for their program monitoring and evaluation purpose. 

WHO and Unicef released the first IYCF indicators definition and measurement guideline in 2008, and indicators were composed into core and optimal categories. In 2021, that guideline was updated, and there was no distinction of indicatory type as before. Attached with the guideline, the WHO and Unicef also provided the standard questionnaires, which capture the information required to calculate the IYCF indicators since the first initial publication. 

Although it was published in 2008 and many humanitarian organizations and countries' health ministries are implementing those indicators, no comprehensive statistical programming package to calculate those indicators was available yet. Therefore, this project is aimed to address this technical gap by providing an easy-to-use `r-package` for calculating IYCF indicators and the `XLS programming form` (for deploying at any ODK feature-based platform) for mobile phone/tablet based data collection. 


## Objective 

+ To develop the `r-commends` package to generate IYCF indicators according to the indicators' definition provided by the WHO/UNICEF 2021 guideline.
+ To develop the XLS programming form based on WHO/UNICEF IYCF indicators standard questionnaires. 
+ To publish the `riycf` package at The Comprehensive R Archive Network 
+ To deploy the website to explain the IYCF indicators and demonstration project on application of r-package
+ To draft the concept note and flow-chart of the shiny app (using this `riycf` package) to deploy the dashboard indicator results report and data visualization. 


## Project Organization 

+ [Professor Rebecca Wolfe](https://harris.uchicago.edu/directory/rebecca-wolfe): Academic Supervisor 
+ [Ernest Guevarra](https://ernest.guevarra.io/): R-expert and Technical Resource Person 
+ Nicholus Tint Zaw: Student and Lead author of the package 


## Work-flow Management 

+ A weekly update will share with the academic supervisor and r-expert 
+ Hold regular bi-weekly meetings with the academic supervisor to update the project progress and other project-related issues 
+ Hold regular weekly meetings with r-expert to review the codes 
+ Use git-hub platform as of version control, coding task management and publication 


## Timeline and Project Milestones 

**Duration**: Spring Quarter (28th March 2022 - 4th June 2022)  


**Milestones** 

+ Step 1: XLS form development 
+ Step 2: Completion of Breastfeeding related indicators 
+ Step 3: Completion of Complementary related indicators 
+ Step 4: Development of general user guideline (for r-package) 
+ Step 5: Submit publication at CRAN 
+ Step 6: Development of Shiny app (conceptual note and flow-chart) 


## Reference Documents and Reading 

+ [\textcolor{blue}{the Indicators for assessing infant and young child feeding practices: definitions and measurement methods}](https://www.who.int/publications/i/item/9789240018389) 
+ [\textcolor{blue}{R Packages: Organize, Test, Document and Share your Code}](https://r-pkgs.org/index.html) 






